サービス終了のお知らせを掲載
codeforchiba/togo pull request #27
Opened 2020-12-31 01:57 UTC by k-hata

サービス終了のお知らせを掲載しました。
フォントやサイズは同ページのその他説明にあわせてました。
![image](https://user-images.githubusercontent.com/3695706/103390254-cfc50b80-4b56-11eb-9de8-8ace92b177a6.png)

2020-12-31 06:12 UTC, misopeso requested changes

2020-12-31 06:12 UTC, misopeso commented on components/logo.vue
> +      <p>いままで「おうちで食べようin千葉」をご利用いただき、誠にありがとうございます。引き続き、code for chibaのサービスを利用いただけますことを心よりお待ち申し上げます。</p>
「code for chiba」 を 「NPO法人 Code for Chiba」 に変更お願いします！

2020-12-31 07:39 UTC, misopeso requested changes

2020-12-31 07:39 UTC, misopeso commented on components/logo.vue
>      </v-col>
ここに入れちゃうと全ページに入っちゃうので、トップページのみでよいかと思います！

2020-12-31 12:30 UTC, k-hata commented on components/logo.vue
> +      <p>いままで「おうちで食べようin千葉」をご利用いただき、誠にありがとうございます。引き続き、code for chibaのサービスを利用いただけますことを心よりお待ち申し上げます。</p>
変更しました。

2020-12-31 12:30 UTC, k-hata commented on components/logo.vue
>      </v-col>
トップページのみに修正しました。

2020-12-31 14:43 UTC, misopeso requested changes

2020-12-31 14:43 UTC, misopeso commented on pages/index.vue
> +      <v-col cols="12" class="text-left text-md-center">
すいませんが、もう 1つだけ。。。PC でみると、折返しがあって中央揃えだと見づらくなっちゃうので、 text-md-center はないほうがよいと思います。

<img width="1378" alt="Screen Shot 2020-12-31 at 23 41 04" src="https://user-images.githubusercontent.com/614339/103414539-b3aa8400-4bc1-11eb-9a37-9f26b91f55d6.png">

2021-01-01 06:22 UTC, k-hata commented on pages/index.vue
> +      <v-col cols="12" class="text-left text-md-center">
あー、折り返し発生してましたか。自分の所では発生していなかったので気づかず。
センタ寄せをやめて、文字の表示領域をお店のグリッドに合わせるようにしました。

![image](https://user-images.githubusercontent.com/3695706/103434470-1a24b600-4c45-11eb-95e1-238d4a344415.png)

2021-01-01 21:41 UTC, misopeso approved these changes
LGTM!

2021-01-01 21:41 UTC, merged